### PR TITLE
Update Adafruit_Trellis.h

### PR DESCRIPTION
**Pull request by receter**
As proposed in this thread: https://github.com/adafruit/Adafruit_Trellis_Library/issues/8

### CODE REVIEW

**Comment by ladyada** [comment]
k!

**Comment by receter** [comment]
Why not? It took me some time to figure it out, others will run into the same problem. Has my fix some drawbacks that I am not aware of? Let me now.

**Comment by ladyada** [comment]
i added it :) i recommitted with the #def in a slightly different place :) plz do a git pull to get it, thx!!!

**Comment by receter** [comment]
Nice, thanks!

**Pull request closed without merging**
